[package]
name = "backend"
version = "0.2.12"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.75"
async-trait = "0.1.73"
base64 = "0.21.4"
md5 = "0.7.0"
regex = "1.9.5"
reqwest = { version = "0.11.20", default-features = false, features = [
	"json",
	"rustls-tls",
] }
serde = { version = "1.0.188", features = ["derive"] }
serde_json = "1.0.106"
serde_urlencoded = "0.7.1"
urlencoding = "2.1.3"

[dev-dependencies]
tokio = { version = "1.32.0", features = ["full"] }

