[package]
name = "backend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.68"
async-trait = "0.1.60"
base64 = "0.20.0"
md5 = "0.7.0"
openssl = { version = "0.10.45", optional = true }
regex = "1.7.0"
reqwest = { version = "0.11.13", default-features = false, features = [
	"json",
	"rustls-tls",
] }
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.91"

[dev-dependencies]
tokio = { version = "1.23.0", features = ["full"] }

