[package]
name = "backend"
version = "0.2.12"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.71"
async-trait = "0.1.68"
base64 = "0.21.2"
md5 = "0.7.0"
regex = "1.8.2"
reqwest = { version = "0.11.18", default-features = false, features = [
	"json",
	"rustls-tls",
] }
serde = { version = "1.0.163", features = ["derive"] }
serde_json = "1.0.96"
serde_urlencoded = "0.7.1"
urlencoding = "2.1.2"

[dev-dependencies]
tokio = { version = "1.28.1", features = ["full"] }

