[package]
name = "backend"
version = "0.2.10"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.70"
async-trait = "0.1.68"
base64 = "0.21.0"
md5 = "0.7.0"
regex = "1.7.3"
reqwest = { version = "0.11.15", default-features = false, features = [
	"json",
	"rustls-tls",
] }
serde = { version = "1.0.159", features = ["derive"] }
serde_json = "1.0.95"
serde_urlencoded = "0.7.1"
urlencoding = "2.1.2"

[dev-dependencies]
tokio = { version = "1.26.0", features = ["full"] }

