[package]
name = "backend"
version = "0.2.9"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.68"
async-trait = "0.1.62"
base64 = "0.21.0"
md5 = "0.7.0"
regex = "1.7.1"
reqwest = { version = "0.11.13", default-features = false, features = [
	"json",
	"rustls-tls",
] }
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.91"
serde_urlencoded = "0.7.1"
urlencoding = "2.1.2"

[dev-dependencies]
tokio = { version = "1.24.2", features = ["full"] }

