[package]
name = "cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.68"
clap = { version = "4.0.32", features = ["derive"] }
reqwest = { version = "0.11.13", default-features = false }
tokio = { version = "1.23.0", features = ["full"] }
backend = { path = "../backend" }

[features]
rustls = ["reqwest/rustls-tls"]
