[package]
name = "cli"
version = "0.2.12"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.75"
clap = { version = "4.4.11", features = ["derive"] }
reqwest = { version = "0.11.22", default-features = false, features = [
	"rustls-tls",
] }
tokio = { version = "1.34.0", features = ["full"] }
backend = { path = "../backend", default-features = false }
