[package]
name = "cli"
version = "0.2.10"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.69"
clap = { version = "4.1.9", features = ["derive"] }
reqwest = { version = "0.11.14", default-features = false, features = [
	"rustls-tls",
] }
tokio = { version = "1.26.0", features = ["full"] }
backend = { path = "../backend", default-features = false }
