[package]
name = "server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.68"
axum = "0.6.1"
backend = { path = "../backend", default-features = false}
clap = { version = "4.0.32", features = ["derive"] }
reqwest = { version = "0.11.13", default-features = false, features = [
	"rustls-tls",
] }
serde = { version = "1.0.152", features = ["derive"] }
tokio = { version = "1.23.0", features = ["full"] }
openssl = { version = "0.10.45", optional = true }
