[package]
name = "server"
version = "0.2.12"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.71"
axum = "0.6.18"
backend = { path = "../backend", default-features = false }
clap = { version = "4.2.7", features = ["derive"] }
reqwest = { version = "0.11.17", default-features = false, features = [
	"rustls-tls",
] }
serde = { version = "1.0.160", features = ["derive"] }
tokio = { version = "1.28.0", features = ["full"] }
tower-http = { version = "0.4.0", features = ["trace"] }
tracing = "0.1.38"
tracing-subscriber = "0.3.17"
