name: CI
on:
  push:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - aarch64-unknown-linux-gnu
          - x86_64-unknown-linux-gnu
          - x86_64-pc-windows-gnu
          - armv7-unknown-linux-gnueabihf
          - arm-unknown-linux-gnueabihf
          - aarch64-unknown-linux-musl
          - x86_64-unknown-linux-musl
          - armv7-unknown-linux-musleabihf
          - arm-unknown-linux-musleabihf

      fail-fast: true
    steps:
      - uses: actions/checkout@main

      - uses: Swatinem/rust-cache@master
        with:
          shared-key: ${{matrix.target}}

      - uses: actions-rs/cargo@master
        with:
          use-cross: true
          command: build
          args: --release --all --target ${{matrix.target}}

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{matrix.target}}
          path: |
            target/${{matrix.target}}/release/server
            target/${{matrix.target}}/release/server.exe
            target/${{matrix.target}}/release/cli
            target/${{matrix.target}}/release/cli.exe

  docker:
    runs-on: ubuntu-latest
    needs:
      - build

    steps:
      - uses: actions/checkout@main

      - uses: actions/download-artifact@v3
        with:
          name: aarch64-unknown-linux-musl
          path: arm64

      - uses: actions/download-artifact@v3
        with:
          name: x86_64-unknown-linux-musl
          path: amd64

      - uses: actions/download-artifact@v3
        with:
          name: armv7-unknown-linux-musleabihf
          path: armv7

      - uses: actions/download-artifact@v3
        with:
          name: arm-unknown-linux-musleabihf
          path: armv6

      - name: Set up QEMU
        uses: docker/setup-qemu-action@master

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@master

      - name: Login to DockerHub
        uses: docker/login-action@master
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: docker build
        uses: docker/build-push-action@master
        with:
          context: .
          push: true
          platforms: |
            linux/arm64
            linux/amd64
            linux/arm/v7
            linux/arm/v6
          tags: tkit1994/stream-url:latest

  release:
    runs-on: ubuntu-latest
    if: "startsWith(github.ref, 'refs/tags/')"
    needs:
      - build

    steps:
      - uses: actions/checkout@main

      - name: Get tag
        id: tag
        uses: dawidd6/action-get-tag@v1

      - name: Dowload release files
        uses: actions/download-artifact@v3
        with:
          path: artifacts

      - name: Archive release files
        run: |
          cd artifacts
          for dirname in *; do
            cd ${dirname}
            tar czvf stream-url-${{ steps.tag.outputs.tag }}.${dirname}.tar.gz *
            cd ..
          done
          find . -name '*.tar.gz' | xargs -i mv {} ${GITHUB_WORKSPACE}

      - name: Upload package to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: "*.tar.gz"
          prerelease: ${{ contains(github.ref, 'alpha') || contains(github.ref, 'beta') }}
          generate_release_notes: true
