name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: rust-toolchain
      with:
        toolchain: stable
        target: aarch64-unknown-linux-gnu
        profile: minimal
        default: true
        
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
